Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -135,17 +135,24 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      # Install AWS CLI
+      
+   # Install AWS CLI
       - name: Install AWS CLI
         run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-
-          sudo apt-get update -y
-          sudo apt-get install -y unzip
-
-          unzip awscliv2.zip
-
-          sudo ./aws/install --update
+          if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found. Installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            
+            sudo apt-get update -y
+            sudo apt-get install -y unzip
+            
+            # Use -o to force overwrite without prompting, and -q for quiet
+            unzip -o -q awscliv2.zip
+            
+            sudo ./aws/install --update
+          else
+            echo "AWS CLI is already installed. Skipping installation."
+          fi
 
       # Configure AWS Credentials
       - name: Configure AWS Credentials
